### ISSUE TITLE
WordPress 5.7 support

### ISSUE THREAD

**Issue by johnbillion** [humanmade/Cavalcade#109]
WordPress 5.7 will allow the functions that write to the cron array to return a `WP_Error` object on failure. The various cron filters will also conditionally accept and return `WP_Error` objects. Ref: https://core.trac.wordpress.org/ticket/49961

Cavalcade should work out of the box with no changes, but it would be good to support the new `$wp_error` parameters and return a `WP_Error` instead of boolean false where necessary.

I'm happy to work on a PR.

**Comment by roborourke** [comment]
Thanks for flagging this @johnbillion! If you have time that'd be really helpful but seems like maintenance we'll need to for Altis v7 if you don't get to it regardless.

**Comment by johnbillion** [comment]
I don't think I'm going to have time for this actually. Like I said, Cavalcade will work out of the box with this change but the addition of support for optional `WP_Error` objects would be good.

**Comment by roborourke** [comment]
Fixed in #119
