### ISSUE TITLE
Existing jobs

### ISSUE THREAD

**Issue by henrywright** [humanmade/Cavalcade#112]
Hey

What will happen to existing jobs if I install Cavalcade? Do they get migrated to the new table?

**Comment by rmccue** [comment]
Jobs aren’t migrated, no. Provided that your code is conditionally scheduling recurring jobs, it’ll see that it’s not scheduled when you activate Cavalcade, and will then register itself, so migration generally isn’t necessary for existing recurring jobs.

(One-off jobs you’d need to migrate if you want to keep them.)

**Comment by henrywright** [comment]
Got you. Thanks @rmccue
