### ISSUE TITLE
Quick questions

### ISSUE THREAD

**Issue by agenceKanvas** [humanmade/Cavalcade#121]
Hi ! Looks like an awesome project. Before setting it up, I'd like to ask some questions.
- If I understand well, it's 1 install of cavalcade per site ? Or can it manage many websites on different servers ? 
- Did you already try it with a woocommerce subscription ? Just to be sure of the compatibility. 
Thanks a lot !

**Comment by kadamwhite** [comment]
Hello, @agenceKanvas! If I understand your question correctly, Cavalcade is designed for use on a multisite network, where one WordPress install (and one Cavalcade plugin install) manages multiple individual sites. You would need to install Cavalcade on each server on which you have WordPress running, if you are running multiple different sites or networks on different servers.

**Comment by rmccue** [comment]
> Did you already try it with a woocommerce subscription ? Just to be sure of the compatibility.

WooCommerce uses a system called Action Scheduler for reliably running wp-cron jobs, and AS is compatible with Cavalcade; we run WooCommerce using Cavalcade in production at scale.

Hope that helps! Closing out, but feel free to follow up with further.
