### ISSUE TITLE
Add a WP-CLI command to stop jobs

### ISSUE THREAD

**Issue by BronsonQuick** [humanmade/Cavalcade#13]
There's a chance that you might end up with a stack of jobs running at once which can throttle a server. We should consider adding a command to stop jobs from running.

@rmccue does that sound like a good idea? Can you forsee any issues or reasons not to add a command for that?

**Comment by rmccue** [comment]
This is already handled by the system's supervisor, no need for a custom command.

```
service cavalcade stop
```
