### ISSUE TITLE
Why did you decide to start a new project when you already had Job Agency?

### ISSUE THREAD

**Issue by danielbachhuber** [humanmade/Cavalcade#2]

**Comment by rmccue** [comment]
This attacks the problem from a slightly different angle by integrating deeply into the existing wp-cron system. It's also inherently multisite from the start, using wp-cli/full sunrise for the site routing, which we needed on Happytables in particular.

This one's written from scratch to be more of a drop-in, but it's certainly inspired by both Job Agency as well as other systems like Resque and beanstalkd.
