### ISSUE TITLE
Is cavalcade reliable?

### ISSUE THREAD

**Issue by tillkruss** [humanmade/Cavalcade#22]
Hi!

We are using Cavalcade for a crucial part of our system. Can we be 100% certain that failed jobs will remain in the `cavalcade_jobs` table so we can re-run them at a later point in time, or is there any chance that they might disappear?

Thanks!

**Comment by rmccue** [comment]
There's absolutely no code in Cavalcade (either the plugin or runner) to clear out failed jobs, and Cavalcade is designed for concurrency, so as long as you trust MySQL, there's no chance they'll disappear. :)
