### ISSUE TITLE
When recurring jobs fail, future iterations fail + WordPress still thinks it'll run

### ISSUE THREAD

**Issue by dd32** [humanmade/Cavalcade#23]
Ran into an interesting scenario today where a daily recurring job failed last week and it wasn't queued again / re-run.

In the `cavalcade_jobs` table, the `status` was `'failed'`
- `wp_next_scheduled( $job )` returned the date for the next time after that failed run when it should have run (The plugin queries for jobs which are `status != 'complete'` to return in the cron array)
- Cavalcade failed to run the job the next day as the job failed, and it was only looking for `status = 'waiting'`.

This ended up in a situation where WordPress thought the job was queued and Cavalcade didn't attempt to run it.

In this case, I manually reset the `status` field for the jobs in question to `waiting` and it continued on it's way.

**Comment by dd32** [comment]
recurring jobs set `status = 'waiting'` after successful runs, so it runs again.

I'm unsure if the failure is the runner or the plugin (or both). It would make sense that the plugin would only show jobs listed as `status = 'waiting'`, which will cause `wp_next_scheduled()` not to show a date for failed jobs. It would also make sense for the Runner not to set the job as failed for a recurring job.

Changing the plugin to only return `waiting` jobs would mean that if a recurring job failed, there'd be multiple entries in the `cavalcade_jobs` table for that blog/hook - I'm unsure if that's a problem though.

**Comment by ocean90** [comment]
> In this case, I manually reset the `status` field for the jobs in question to `waiting` and it continued on it's way.

When doing that then for some reasons the job is running every second for a while. Is that because it's re-running all the jobs which didn't run before?

<img width="375" alt="bildschirmfoto 2016-11-13 um 15 08 15" src="https://cloud.githubusercontent.com/assets/617637/20246238/101b3b72-a9b3-11e6-82ff-8a8c14d1d2bb.png">

**Comment by dd32** [comment]
> When doing that then for some reasons the job is running every second for a while. Is that because it's re-running all the jobs which didn't run before?

Yes, unless you update the `nextrun` field too. for most jobs it doesn't matter, but that job which was running every minute had a fair bit of iterations to catch up on.

**Comment by rmccue** [comment]
Correct; if you change it back to `waiting`, Cavalcade will continue running it normally, and it doesn't skip cycles. If you have a task that runs every minute, and it stops for five minutes, it will have to run 5 times before it catches back up.

**Comment by dd32** [comment]
I think the intention of #27 was to fix this, which I'm assuming it did as it hasn't been an issue on WordPress.org in years.
