### ISSUE TITLE
Does Cavalcade kills any long running process 

### ISSUE THREAD

**Issue by vishaldodiya** [humanmade/Cavalcade#50]
I am using one long process which takes about an hour to get completed. but the process get in failed status before it get completed.

**Comment by rmccue** [comment]
Apologies for the delayed reply.

Cavalcade doesn't kill processes with a timeout, but it's possible that your system has killed it for running too long, or for running out of memory. Check your `wp_cavalcade_logs` table for the exit status of your process.
