### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by CountryNerd** [humanmade/Cavalcade#52]
Parse error: syntax error, unexpected '[', expecting ')' in /opt/wordpress/wp-content/plugins/Cavalcade-master/inc/namespace.php on line 22

**Comment by rmccue** [comment]
Cavalcade requires at least PHP 5.4+, although I'd highly recommend using at least PHP 7.0. We don't intend on providing compatibility with PHP 5.3.

**Comment by CountryNerd** [comment]
Thank you. You may close the ticket. I understand.
