### ISSUE TITLE
Does Cavalcade benefit from the recent improvements to WP? 

### ISSUE THREAD

**Issue by archon810** [humanmade/Cavalcade#67]
Specifically this: https://core.trac.wordpress.org/ticket/32656.
https://core.trac.wordpress.org/ticket/15148#comment:22

**Comment by rmccue** [comment]
Currently, it doesn't use these, however 32656 was filed as a result of Cavalcade and fixed by my colleague @peterwilsoncc, so we'll switch to using it in the future. :)
