### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by prontojoe** [humanmade/Cavalcade#7]
Can you provide step to install you plugin ?
I get error when install on mu plugin
PHP Fatal error:  Class 'WP_CLI_Command' not found in /var/www/wp-content/mu-plugins/class-command.php on line 8

I can run wp --info
PHP binary:     /usr/bin/php5
PHP version:    5.5.9-1ubuntu4.7
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.20.1

what next should I do? 

thank you

**Comment by rmccue** [comment]
You need to put the _directory_ into mu-plugins, not the files individually.
