### ISSUE TITLE
Very many records in the table wp_cavalcade_jobs / wp_cavalcade_jobs

### ISSUE THREAD

**Issue by mihdan** [humanmade/Cavalcade#72]
Can I clear the table or delete records with a status of completed?

![](http://screenshot.kobzarev.com/2018-10-26-1540513202.png)

**Comment by rmccue** [comment]
Yep, you can delete any records with `completed` or `failed` as the status. The only thing to be aware of is deleting `failed` jobs may also cause them to be rescheduled if they're recurring jobs.
