### ISSUE TITLE
Meaningful return values introduced in WP Core are incorrect with Cavalcade

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/Cavalcade#80]
In WordPress/wordpress-develop@e73af26e920264314c4d10419e60044240756001 meaningful return values were introduced for cron functions, often these return the result of `update_option()` for the cron array.

As the Cavalcade connector short circuits the cron array from updating this always returns a `false`. Until the connector is updated to use the hooks added in wordpress/wordpress-develop@a32ea2d35d2fcf7bccf54ff7abfad9a2b49ee360 testing the return values will fail.

Blame is an ugly word but it should be noted both of the commits linked above were done by the same person. Me.

**Comment by archon810** [comment]
> Blame is an ugly word but it should be noted both of the commits linked above were done by the same person. Me.

An instant classic.
