### ISSUE TITLE
Bootstrap Cron filters prior to `plugins_loaded` firing

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/Cavalcade#83]
The cron array may be accessed prior to the `plugins_loaded` action firing, the most likely candidates are:

* `muplugins_loaded`
* `plugin_loaded` added in WP 5.1
* `muplugin_loaded` added in WP 5.1

Running `Connector\bootstrap()` as the plugin is `require`d will filter the cron array as soon as the code is available.

On the downside, the `is_installed()` check would probably need to be included in the filters but as it's cached, this shouldn't cause too much of a problem.

**Comment by peterwilsoncc** [comment]
Related: [WP Core ticket #49824](https://core.trac.wordpress.org/ticket/49824) in 5.4 bumps the priority on this a little as a cron job is scheduled prior to the `plugins_loaded` hook by the site health component. 

cc @roborourke

**Comment by archon810** [comment]
Any updates?

**Comment by archon810** [comment]
Related: https://github.com/humanmade/Cavalcade/issues/101.

**Comment by roborourke** [comment]
No updates yet, probably because we don't use the site health stuff on our hosting it hasn't really come up as an issue for us.

So I guess the best we can do is just to run the initial bootstrap function immediately when the plugin file is loaded.

**Comment by roborourke** [comment]
Fix released in 2.0.1
