### ISSUE TITLE
Installation instructions: dependency on wp-cli

### ISSUE THREAD

**Issue by mwithheld** [humanmade/Cavalcade#9]
I dropped all 4 of the files into the mu-plugins folder
class-command.php
class-job.php
connector.php
plugin.php

And on reload immediately the site died with a 500 error
PHP Fatal error:  Class 'WP_CLI_Command' not found in wp-content/mu-plugins/class-command.php on line 8

Can you please update or add detail to your install instructions?

**Comment by rmccue** [comment]
You need to clone the whole of Cavalcade into a subdirectory of `mu-plugins`, not directly into the directory. That is you should have `mu-plugins/cavalcade/plugin.php` and etc.

I'll add a note that it's required though.
